### ISSUE TITLE
unsupported index

### ISSUE THREAD

**Issue by kkiran33** [SimonSelg/egghead-downloader#10]
/usr/local/lib/node_modules/egghead-downloader/dist/app.js:15
    for (const { url, filename } of videos) {
               ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by SimonSelg** [comment]
Hey,

which node version are you using? Maybe not >= 6.0?

**Comment by kkoscielniak** [comment]
Confirmed. I had 5.3.0, after upgrading to 6.6.0 everything works as it should.

**Comment by SimonSelg** [comment]
👍 good to hear! I'll merge #11 later (or roll my own version of it) so that this shouldn't be an issue anymore (seriously, I didn't expect so may people, actually, I never expected anyone to use this, that's why I didn't add compatibility  with older node version).

**Comment by jarst** [comment]
This issue should be still open - my PR is still waiting for merge...
