### ISSUE TITLE
i cant run it >S

### ISSUE THREAD

**Issue by dantejauregui** [SimonSelg/egghead-downloader#14]
hello SIMON

i tried: egghead-downloader -c https://egghead.io/series/getting-started-with-redux really-awesome-series

but in my console i receive this fail meesage:

/usr/lib/node_modules/egghead-downloader/dist/app.js:4
let doTheMagic = (() => {
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

how can we do to run it correctly

**Comment by overra** [comment]
> Currently it requires node >= v.6.0.0

Hi @dantejauregui it looks like you need to update node to a version >=6. If you need to use a version <6 you can install [nvm](https://github.com/creationix/nvm) which makes it really easy to switch between versions of node.

**Comment by SimonSelg** [comment]
On a sidenote, I should probably transpile it for lower node versions as this seems to be a recurring problem.
