### ISSUE TITLE
Tool failing (Unexpected token {)

### ISSUE THREAD

**Issue by gorkamolero** [SimonSelg/egghead-downloader#4]
Hey there!

First, thanks for building this. It's throwing a syntax error:

`/usr/local/lib/node_modules/egghead-downloader/dist/app.js:15
    for (const { url, filename } of videos) {
               ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3`

Do you know anything about this?

**Comment by SimonSelg** [comment]
Hey! Which node version are you using? Is it by any change lower then 6.0?

**Comment by gorkamolero** [comment]
Yes, yes it is. I'm guessing that's the problem! Thanks!

**Comment by SimonSelg** [comment]
Np. If upgrading is an issue for you, I could transpile it for es5 (node < 6). Let me know if that'd help you.
